site_name: The DocuDex
site_url: https://docudex.am-s.app
site_description: Guides for players and integration details for modders
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: slate
      primary: light blue
      accent: light blue
    - scheme: default
      primary: teal
      accent: blue

plugins:
  - search
  - glightbox:
      zoomable: true
      effect: zoom
      auto_caption: false
  - macros:
      module_name: GenerateChangelog

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - meta
  - attr_list
extra:
  search:
    language: en
    separator: '[\s\-]+'
extra_css:
  - overrides.css

nav:
  - Home: index.md
  
  - LACC:
      - Home: LACC/index.md
      - Players:
          - Installation: LACC/players/install.md
          - Usage: LACC/players/usage.md
          - Troubleshooting: LACC/players/troubleshooting.md
      - Servers:
          - Installation: LACC/servers/install.md
          - Configuration: LACC/servers/config.md
          - API: LACC/servers/API.md
          - ScriptCommands: LACC/servers/scriptcommands.md
      - Modders:
          - MCI: LACC/modders/mci.md
      - Changelog: LACC/changelog.md
  